apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
    name: sif-ettersending
    namespace: default
    labels:
        team: dusseldorf
spec:
    image: {{ image }}
    port: 8080
    liveness:
        path: /familie/sykdom-i-familien/soknad/ettersending/health/isAlive
        initialDelay: 20
        timeout: 1
        periodSeconds: 5
        failureThreshold: 10
    readiness:
        path: /familie/sykdom-i-familien/soknad/ettersending/health/isReady
        initialDelay: 20
        timeout: 1
    resources:
        limits:
            cpu: 2000m
            memory: 512Mi
        requests:
            cpu: 50m
            memory: 128Mi
    ingresses:
        - https://www-q0.nav.no/familie/sykdom-i-familien/soknad/ettersending
        - https://sif-ettersending.nais.oera-q.local
    replicas:
        min: 1
        max: 1
        cpuThresholdPercentage: 90
    prometheus:
        enabled: true
        path: /metrics
    vault:
        enabled: false
    env:
        - name: DEKORATOR_URL
          value: https://www.nav.no/dekoratoren/?simple=true
        - name: API_URL
          value: https://k9-ettersending-api-q.nav.no
        - name: PUBLIC_PATH
          value: /familie/sykdom-i-familien/soknad/ettersending
        - name: LOGIN_URL
          value: https://loginservice-q.nav.no/login?redirect=https://www-q0.nav.no/familie/sykdom-i-familien/soknad/ettersending

